import QRCode from "qrcode";
import { supabaseServer, supabaseConfigured } from "@/lib/supabase/server";
import CopyButton from "./CopyButton";

/**
 * Deposit panel.
 *
 * Shows ONLY an address already assigned to this user in deposit_addresses,
 * and renders the QR server-side so no address ever passes through client JS.
 *
 * If no address exists, this says so rather than falling back to a shared one.
 * A single static address shared between users makes deposits unattributable:
 * two people paying in, and you cannot tell whose money is whose. Matching by
 * amount fails the first time two users send the same figure.
 *
 * Addresses get created by your payment processor (Coinbase Commerce, BitPay,
 * Fireblocks) or derived from an HD wallet at a unique index — see
 * app/api/webhooks/deposits/route.ts.
 */
export default async function DepositPanel({ userId }: { userId: string }) {
  // Without Supabase there are no addresses to show. Say so plainly rather
  // than throwing and taking the whole dashboard down with a 500.
  if (!supabaseConfigured()) {
    return (
      <div className="blank">
        <p className="blank__lead">Deposits need a database.</p>
        <p className="blank__body">
          Set NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY, run
          supabase/FULL_SCHEMA.sql, then connect a payment processor to the
          deposit webhook. Addresses appear here once assigned.
        </p>
      </div>
    );
  }

  const sb = await supabaseServer();

  const [{ data: assets }, { data: addresses }, { data: pending }] = await Promise.all([
    sb
      .from("assets")
      .select("symbol, display_name, network, min_deposit, required_confirmations, is_deposit_enabled")
      .eq("kind", "crypto")
      .order("sort_order"),
    sb
      .from("deposit_addresses")
      .select("asset_symbol, address, memo")
      .eq("user_id", userId)
      .eq("is_active", true),
    sb
      .from("pending_deposits")
      .select("asset_symbol, amount, confirmations, required_confirmations, txid"),
  ]);

  const addrFor = new Map((addresses ?? []).map((a) => [a.asset_symbol, a]));
  const enabled = (assets ?? []).filter((a) => a.is_deposit_enabled);

  if (enabled.length === 0) {
    return (
      <div className="blank">
        <p className="blank__lead">Deposits are switched off.</p>
        <p className="blank__body">
          No asset has <code>is_deposit_enabled</code> set. Turn them on in the
          admin panel only after a payment processor is wired to the deposit
          webhook and you have watched one real deposit confirm end to end.
        </p>
      </div>
    );
  }

  const cards = await Promise.all(
    enabled.map(async (a) => {
      const addr = addrFor.get(a.symbol);
      const svg = addr
        ? await QRCode.toString(addr.address, {
            type: "svg",
            margin: 0,
            errorCorrectionLevel: "M",
            color: { dark: "#0b0b0d", light: "#e8e6e0" },
          })
        : null;
      return { asset: a, addr, svg };
    }),
  );

  return (
    <>
      <div className="dep">
        {cards.map(({ asset, addr, svg }) => (
          <article className="dep__card" key={asset.symbol}>
            <header className="dep__head">
              <span className="tbl__sym">{asset.symbol}</span>
              <span className="mono dep__net">{asset.network}</span>
            </header>

            {svg && addr ? (
              <>
                <div
                  className="dep__qr"
                  // Generated by the qrcode package from an address read out of
                  // our own table — not user input.
                  dangerouslySetInnerHTML={{ __html: svg }}
                />
                <p className="mono dep__addr">{addr.address}</p>
                <CopyButton value={addr.address} />
                {addr.memo && (
                  <p className="mono dep__memo">
                    Memo required: {addr.memo}
                  </p>
                )}
              </>
            ) : (
              <p className="dep__none mono">
                No address assigned yet. Request one from the processor.
              </p>
            )}

            <dl className="dep__meta">
              <div>
                <dt className="mono">Minimum</dt>
                <dd className="mono">
                  {asset.min_deposit ?? "—"} {asset.symbol.split("-")[0]}
                </dd>
              </div>
              <div>
                <dt className="mono">Credited after</dt>
                <dd className="mono">{asset.required_confirmations} conf.</dd>
              </div>
            </dl>
          </article>
        ))}
      </div>

      {(pending ?? []).length > 0 && (
        <table className="tbl" style={{ marginTop: "28px" }}>
          <thead>
            <tr>
              <th>Inbound</th>
              <th className="num">Amount</th>
              <th className="num">Confirmations</th>
            </tr>
          </thead>
          <tbody>
            {pending!.map((p) => (
              <tr key={p.txid}>
                <td className="tbl__sym">{p.asset_symbol}</td>
                <td className="num mono">{p.amount}</td>
                <td className="num mono">
                  {p.confirmations}/{p.required_confirmations}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}

      <p className="dnote mono">
        Send only the named asset on the named network to its own address.
        Cross-chain sends are unrecoverable. Nothing appears in your available
        balance until it reaches the confirmation count shown — unconfirmed
        amounts are listed separately above and are never counted as spendable.
      </p>
    </>
  );
}
